name: Flutter Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Flutter action
        uses: subosito/flutter-action@v1.5.3

      - name: Install dependencies
        run: flutter pub get
        
      - name: Build Web
        run: flutter build web --web-renderer html
        
      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          build_dir: build/web
